<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
    <link rel="stylesheet" href="style/style.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="style/main.js"></script>
    <title>Vincent Dev - Book</title>
</head>
<body>
    <header class="col">
        <section id="card-intro" class="row btw">
            <div id="title" class="col btw center max-w">
                <h1>
                    Vincent Caraty <br> Développeur Intégrateur Web 
                </h1>
                <h3>
                    Poste actuel : en recherche d'emploi
                </h3>
            </div>
            <div id="photo" class="img-150 col ard al-center">
                <p><img src="img/vincent_photo.png" alt=""></p>
            </div>
        </section>
        <section class="menu-nav col ard">
            <nav class="screen">
                <ul class="container row btw center al-center">
                    <li><a href="#presentation">Présentation</a></li>
                    <li><a href="#skill">Compétences</a></li>
                    <li><a href="#projets">Projets</a></li>
                    <li><a href="#contact">Contact</a></li>
                    <li><a target="_blank" title="lien vers linkedin" href="https://www.linkedin.com/in/vincent-caraty-a517ba198/"><i class="fab fa-linkedin"></i></a>
                    <a target="_blank" title="télécharger mon CV" href="img/Caraty_Vincent_CV.pdf"><i class="fas fa-file-download"></i>CV</a></li>
                </ul>
            </nav>
            <nav class="mobile">
                <ul class="container row btw center al-center">
                    <li><a href="#presentation"><i class="fas fa-home"></i></a></li>
                    <li><a href="#skill"><i class="fas fa-tools"></i></a></li>
                    <li><a href="#projets"><i class="fas fa-file-signature"></i></a></li>
                    <li><a href="#contact"><i class="fas fa-info-circle"></i></a></li>
                </ul>
            </nav>
        </section>
    </header>
    <main>
        <section id="presentation">
            <p>Passionné depuis mes jeunes années par tout ce qui touche l'informatique j'ai commencé dans la restauration, 
                un BEP à Montargis puis une mention complémentaire en sommellerie dans la belle ville de Tours.</p>
            <p>Une superbe expérience qui m'a permis pendant quinze ans de me former sur la régularité du travail, le déploiement de capacités par l'auto apprentissage, 
                la recherche continuelle d'informations et la manière de s'intégrer au sein d'équipes variées.</p>
            <p>Le développement web commence pour moi lorsque j'ai rejoint une équipe de joueurs passionnés! 
                Leurs proposant de créer une plateforme d'échange où tout le monde pourrait échanger ses impressions 
                sans à avoir à se connecter au jeu, les sites de ce genre étaient rares et Facebook trop peu 
                utilisé encore à ce moment-là! Notre site doté d'un tchat, d'articles et d'un forum, 
                a pris forme grâce aux informations et tutoriel du site-du-zero désormais appelé "
                <a target="_blank" href="https://openclassrooms.com/">openclassrooms</a>" 
                dont les valeurs ne sont plus à prouver aujourd'hui. 
                Site fermé depuis quelques années maintenant malheureusement.</p>
            <p>Ayant eu pas mal d'aventures dans divers restaurants (hôtel-restaurant pour la plupart) et ayant passé mes dernières années en tant que maître d'hôtel, 
                j'ai décidé de transformer ma passion en métier!</p>
            <p>Une formation de développeur intégrateur web à la 3W Académie pour confirmer les connaissances que j'ai rabâchées pendant des années, 
                ça m'a permis de voir ce qu'il fallait faire exactement, et surtout de cadrer correctement mon travail !</p>
        </section>
        <section id="skill" class="row wrap btw">
            <article><h3>PHP</h3><p><i class="fab fa-php"></i></p></article>
            <article><h3>HTML</h3><i class="fab fa-html5"></i></article>
            <article><h3>CSS</h3><i class="fab fa-css3-alt"></i></article>
            <article><h3>JavaScript & Jquery</h3><i class="fab fa-js-square"></i></article>
            <article><h3>Symfony</h3><i class="fab fa-symfony"></i></article>
            <article><h3>SQL PhpMyAdmin</h3><i class="fas fa-database"></i></article>
            <article><h3>Unity & C#</h3><i class="fab fa-unity"></i></article>
            <article><h3>Visual-Studio Code</h3><img src="img/Visual_Studio_Code.png" alt=""></article>
        </section>
        <section id="projets" class="center">
            <h2>Projets en cours</h2>
            <div class="row wrap btw">
                <article data-page="gaming-site">
                    <div>
                        <div>
                            <h3>Gaming-site</h3>
                            <p>Projet personnel pour la validation de certificat de développeur intégrateur web, sur le thème des jeux vidéo et leur communauté</p>
                            <p>(responsive pas encore adapté pour téléphone portable)</p>
                        </div>
                    </div>
                    <p><img src="img/gaming-site.jpg" alt=""></p>
                </article>
                <article data-page="auto-newlife">
                    <div>
                        <div>
                            <h3>Auto-NewLife</h3>
                            <p>Projet d'une entreprise de rénovation/réparation/entretient de voiture anciennes et nouvelles</p>
                            <p>(responsive pas encore adapté pour téléphone portable)</p>
                        </div>
                        <p><img src="img/auto-new-life.jpg" alt=""></p>
                    </div>
                </article>
            </div>
            
            <h3>Projets terminés</h3>
            <article></article>
            
            
        </section>
        <section id="contact" class="row ard center">
            <div id="contact-content">
                <h3>Caraty Vincent</h3>
                <p><i class="fas fa-envelope"></i> : <a href="mailto:vincent.caraty@outlook.fr">vincent.caraty@outlook.fr</a></p>

                <p><a target="_blank" title="lien vers linkedin" href="https://www.linkedin.com/in/vincent-caraty-a517ba198/"><i class="fab fa-linkedin"></i> Lien vers mon profil Linkedin</a></p>
                <p><i class="fas fa-car"></i> Région de recherche d'emploi : Gien 45500 , Orléans, Paris</p>
            </div>
            <div id="cv" class="img-150">
                <p>Télécharger mon CV</p>
                <a target="_blank" title="télécharger mon CV" href="img/Caraty_Vincent_CV.pdf"><img src="img/cv.jpg" alt=""></a>
            </div>
        </section>
    </main>

</body>
</html>