<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@700&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="style/style.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="style/main.js"></script>
    <title>Vincent Dev - Book</title>
</head>
<body>
    <header class="col">
        <section id="card-intro" class="row btw">
            <div id="title" class="col btw center max-w">
                <h1>
                    Vincent Caraty <br> Développeur Intégrateur Web 
                </h1>
                <div class="tlt-info">
                    <h3>
                        Poste actuel : en recherche d'emploi / freelance
                    </h3>
                    <p>Dernière mise à jour : Vendredi 24 Juillet 2020</p>
                </div>
            </div>
            <div id="photo" class="img-150 col ard al-center">
                <p><img src="img/vincent_photo.png" alt=""></p>
            </div>
        </section>
        <section class="menu-nav col ard">
            <nav class="screen">
                <ul class="container row btw center al-center">
                    <li><a href="#presentation">Présentation</a></li>
                    <li><a href="#skill">Compétences</a></li>
                    <li><a href="#projets">Projets</a></li>
                    <li><a href="#contact">Contact</a></li>
                    <li><a target="_blank" title="lien vers linkedin" href="https://www.linkedin.com/in/vincent-caraty-a517ba198/"><i class="fab fa-linkedin"></i></a>
                    <a target="_blank" title="télécharger mon CV" href="img/Caraty_Vincent_CV.pdf"><i class="fas fa-file-download"></i> CV</a></li>
                </ul>
            </nav>
            <nav class="mobile">
                <ul class="container row btw center al-center">
                    <li><a href="#presentation"><i class="fas fa-home"></i></a></li>
                    <li><a href="#skill"><i class="fas fa-tools"></i></a></li>
                    <li><a href="#projets"><i class="fas fa-file-signature"></i></a></li>
                    <li><a href="#contact"><i class="fas fa-info-circle"></i></a></li>
                </ul>
            </nav>
        </section>
    </header>
    <main>
        <section id="presentation">
            <h2>Présentation</h2>
            <p>Passionné depuis mes jeunes années par tout ce qui touche l'informatique j'ai commencé dans la restauration, 
                un BEP à Montargis puis une mention complémentaire en sommellerie dans la belle ville de Tours.</p>
            <p>Une superbe expérience qui m'a permis pendant quinze ans de me former sur la régularité du travail, le déploiement de capacités par l'auto apprentissage, 
                la recherche continuelle d'informations et la manière de s'intégrer au sein d'équipes variées.</p>
            <p>Le développement web commence pour moi lorsque j'ai rejoint une équipe de joueurs passionnés! 
                Leurs proposant de créer une plateforme d'échange où tout le monde pourrait échanger ses impressions 
                sans à avoir à se connecter au jeu, les sites de ce genre étaient rares et Facebook trop peu 
                utilisé encore à ce moment-là! Notre site doté d'un tchat, d'articles et d'un forum, 
                a pris forme grâce aux informations et tutoriel du site-du-zero désormais appelé 
                <a target="_blank" href="https://openclassrooms.com/">Openclassrooms</a> 
                dont les valeurs ne sont plus à prouver aujourd'hui. 
                Site fermé depuis quelques années maintenant malheureusement.</p>
            <p>Ayant eu pas mal d'aventures dans divers entreprises (hôtel-restaurant pour la plupart) travaillant ses dernières années en tant que maître d'hôtel, 
                j'ai décidé de transformer ma passion en métier!</p>
            <p>Une formation de développeur intégrateur web à la <a target="_blank" href="https://3wa.fr">3W Académie</a> pour confirmer les connaissances que j'ai rabâchées pendant des années, 
                ça m'a permis de voir ce qu'il fallait faire exactement, et surtout de cadrer correctement mon travail !</p>
            <h3>Veille actuelle</h3>
            <p><ul>
                <li>Symfony ( Formation & Projet )</li>
                <li>Prestashop ( Formation & Projet )</li>
                <li>Ruby on rails (Formation & Projet )</li>
            </ul></p>
            <h3>Veilles Terminées</h3>
            <p><ul>
                <li>Programmation LUA</li>
                <li>Wordpress</li>
                <li>Utilisation Git & GitHub</li>
                <li>Gestion de projet avec méthodologie en cascade</li>
            </ul></p>
        </section>
        <section id="skill" >
            <h2>Compétences</h2>
            <div   class="skill row wrap btw">
                <article><h3>PHP</h3><p><i class="fab fa-php"></i></p></article>
                <article><h3>HTML</h3><i class="fab fa-html5"></i></article>
                <article><h3>CSS</h3><i class="fab fa-css3-alt"></i></article>
                <article><h3>JavaScript & Jquery</h3><i class="fab fa-js-square"></i></article>
                <article><h3>Symfony</h3><i class="fab fa-symfony"></i></article>
                <article><h3>SQL PhpMyAdmin</h3><i class="fas fa-database"></i></article>
                <article><h3>Unity & C#</h3><i class="fab fa-unity"></i></article>
                <article><h3>Visual-Studio Code</h3><img src="img/Visual_Studio_Code.png" alt=""></article>

            </div>
        </section>
        <section id="projets" class="center">
            <h2>Projets en cours</h2>
            <p>Vous pouvez retrouver la liste de mes projets public Web et lua sur <a href="https://github.com/yenaulrik" target="_blanc">github</a> </p>
            <div class="row wrap btw">
                <article data-page="prestashop01">
                    <div>
                        <div>
                            <h3>Prestashop / React</h3>
                            <p><em>commencé le ?/?</em></p>
                            <p>Projets en négociation</p>
                        </div>
                        <p><img src="https://place-hold.it/350x450" alt=""></p>
                    </div>
                </article>
                <article data-page="auto-newlife-2">
                    <div>
                        <div>
                            <h3>Auto-NewLife</h3>
                            <p><em>recommencé le 20/07</em></p>
                            <p>Projet en cours <br />Vérification du contenu, refonte du JS, et finitions du responsive</p>
                        </div>
                        <p><img src="img/ANL-projet2.png" alt=""></p>
                    </div>
                </article>
            </div>
            
            <h3>Projets terminés</h3>

            <div class="row wrap btw">
                <article data-page="SymBNB">
                    <div>
                        <div>
                            <h3>SymBNB</h3>
                            <p><em>fini le 01/04</em></p>
                            <p>Cours annimé par <a href="https://www.linkedin.com/in/lior-chamla/">Lior Chamla</a> (Projet redémarré suite au changements du cours)</p>
                            
                        </div>
                    </div>
                    <p><img src="img/SymBNB.png" alt=""></p>
                </article>
                <article data-page="gaming-site">
                    <div>
                        <div>
                            <h3>Gaming-site</h3>
                            <p><em>commencé le 01/02 fini le 22/03</em></p>
                            <p>Projet personnel pour la validation de certificat de développeur intégrateur web, sur le thème des jeux vidéo et leur communauté</p>
                            
                        </div>
                    </div>
                    <p><img src="img/gaming-site.png" alt=""></p>
                </article>
                <article data-page="auto-newlife">
                    <div>
                        <div>
                            <h3>Auto-NewLife</h3>
                            <p><em>commencé le 15/02 fini le 05/03</em></p>
                            <p>Projet d'une entreprise de rénovation/réparation/entretient de voiture anciennes et nouvelles</p>
                            
                        </div>
                        <p><img src="img/auto-new-life.jpg" alt=""></p>
                    </div>
                </article>
                <article data-page="projets-3wa">
                    <div>
                        <div>
                            <h3>Projets 3w Academy</h3>
                            
                            <p>Liste des nombreux projets travaillés en cours lors de la formation de développeur web</p>
                            
                        </div>
                        <p><img src="img/projets-3wa.png" alt=""></p>
                    </div>
                </article>
            </div>
            
        </section>
        <section id="contact" class="row ard center">
            <div id="contact-content">
                <h3>Caraty Vincent</h3>
                <p><i class="fas fa-envelope"></i> : <a href="mailto:vincent.caraty@outlook.fr">vincent.caraty@outlook.fr</a></p>

                <p><a target="_blank" title="lien vers linkedin" href="https://www.linkedin.com/in/vincent-caraty-a517ba198/"><i class="fab fa-linkedin"></i> Lien vers mon profil Linkedin</a></p>
                <p><i class="fas fa-car"></i> Région de recherche d'emploi : Gien 45500 , Orléans, Paris</p>
            </div>
            <div id="cv" class="img-150">
                <p>Télécharger mon CV</p>
                <a target="_blank" title="télécharger mon CV" href="img/Caraty_Vincent_CV.pdf"><img src="img/cv.jpg" alt=""></a>
            </div>
        </section>
    </main>

</body>
</html>